auth_project/auth_app/urls.py
from django.conf.urls import url
from auth_app import views

#Template URLs
app_name='auth_app'

urlpatterns=[
    url(r'^register/$',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login')
]

auth_project/auth_project/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from auth_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^auth_app/',include('auth_app.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^special/$',views.special,name='special')
]

auth_project/auth_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
#This is model class to add information that the dafault user doesn't have
class UserProfileInfo(models.Model):

    #Create a relationship between this model and User in django-admin
    user = models.OneToOneField(User)

    #Add any additional attributes you want
    portfolio_site=models.URLField(blank=True)
    picture=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        #Buit-in attribute of django.contrib.auth.models.User models
        return self.user.username

auth_project/auth_app/forms.py
from django import forms
from django.contrib.auth.models import User
from auth_app.models import UserProfileInfo


class UserForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields =('portfolio_site','picture')

auth_project/auth_app/views.py
from django.shortcuts import render
from auth_app.forms import UserForm,UserProfileInfoForm

#imports for creating log in Page
from django.contrib.auth import authenticate,login,logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
# Create your views here.
def index(request):
    return render(request,'auth_app/index.html')

@login_required
def special(request):
    return HttpResponse("You are now logged in!!")


@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    registered=False

    if request.method=="POST":
            user_form = UserForm(data=request.POST)
            profile_info_form = UserProfileInfoForm(data=request.POST)

            if user_form.is_valid() and profile_info_form.is_valid():

                user = user_form.save()
                user.set_password(user.password)
                user.save()

                profile=profile_info_form.save(commit=False)
                profile.user=user

                if 'picture' in request.FILES:
                    profile.picture=request.FILES['picture']

                profile.save()
                registered=True
            else:
                    print(user_form.errors,profile_info_form.errors)

    else:
            user_form =UserForm()
            profile_info_form=UserProfileInfoForm()

    return render(request,'auth_app/registration.html',{'user_form':user_form,
                    'profile_info_form': profile_info_form,
                    'registered':registered})


def user_login(request):
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        #authenticate returns the user object that we store in "user"
        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("Account not active,please log in.")

        else:
            print('Someone tried to login and failed')
            print('Username:{} and password : {}'.format(username,password))
            return HttpResponse("Invalid Login,please ensure the details are correct.")
    else:
        return render(request,'auth_app/login.html',{})

auth_project/templates/auth_app/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">
          <li> <a class="navbar-brand" href="{%url 'index'%}">Home</a></li>
          <li> <a class="navbar-link"href="{%url 'auth_app:register' %}">Register</a></li>
          <li> <a class="navbar-link"href="{%url 'admin:index'%}">Admin</a></li>

          {%  if user.is_authenticated %}
            <li> <a class="navbar-link" href="{%url 'logout' %}">Log out</a> </li>
          {% else %}
            <li> <a class="navbar-link" href="{%url 'auth_app:user_login' %}">Log in</a> </li>
          {% endif %}

        </ul>
      </div>
    </nav>
    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>

  </body>
</html>

auth_project/templates/auth_app/index.html
<!DOCTYPE html>
{% extends "auth_app/base.html" %}

{%  block body_block %}
<div class="jumbotron">
    <h1>Welcome to the Home Page.</h1>
</div>
{% endblock %}

auth_project/templates/auth_app/login.html
{% extends 'auth_app/base.html' %}

{% block body_block %}
<div class="jumbotron">
  <h1>Log in to continue</h1>
  <form action="{% url 'auth_app:user_login' %}" method="post">
    {% csrf_token %}
     <label for="username">Username:</label><br>
     <input type="text" name="username" placeholder="Username"><br>
     <label for="password">Password:</label><br>
     <input type="password" name="password" placeholder="Password"><br>
     <input type="submit" name="" value="Log in">
  </form>


</div>
{% endblock %}

auth_project/templates/auth_app/registration.html
{%extends "auth_app/base.html"%}
{% load staticfiles %}
{% block body_block %}
  <div class="jumbotron">
    {% if registered %}
      <h1>Thanks for registering!</h1>
    {% else %}
      <h1>Register Here!</h1>
      <h3>Fill up the following form.</h3>

      <form  method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_info_form.as_p }}
        <input type="submit" name="" value="Register">
      </form>

    {% endif %}
  </div>


{% endblock %}